### ISSUE TITLE
Out of Date

### ISSUE THREAD

**Issue by RayJ95** [Kukiwon/rfduino-swift#1]
Hello! Sorry to bring out an old project, but I was wondering of you have updated this project for Xcode 9.2? I am really interested in building this project but it seems impossible to use right now. 

Thanks!

**Comment by Kukiwon** [comment]
Hi Ray,

Thanks for your interest! I haven't tried it yet. You might be able to use the Swift Migration Assistant in Xcode to convert the project to the latest standards. More on this is explained [here](https://swift.org/migration-guide-swift3/).

Cheers

**Comment by RayJ95** [comment]
This worked! If you try to do this in one step, it does not work, i.e. Xcode 7.2.1 to 9.2. You have to convert in shorter steps, such as going from Xcode 7.2.1 -> 7.3.1 -> 8.0 -> 8.3.3 -> 9.0 -> 9.2. I ended up trying this several ways and I was most successful when I updated to every version in between the original and the most recent.

Thanks!

**Comment by Kukiwon** [comment]
That's great @RayJ95 ! I would be happy to merge a pull request with the updated code. Cheers.

**Comment by RayJ95** [comment]
Github won't let me do a pull request? I've changed the files quite a bit now, sorry about that. I do have one more question for you if you don't mind:

I want to display a number value that the RFDuino sends via bluetooth in a new view controller; what would the command be for that? I already have the view and the view controller set up, I just can't figure out the right variable. Any help is seriously appreciated!

Thanks,
Ray

**Comment by Kukiwon** [comment]
Hi Ray, I replied you via mail.
